import './components/swiper.js';
import './components/tabs.js';
import './components/quiz.js';
import './components/acardion.js';
import './components/credit.js';
import './components/modal.js';
import './components/slider.js';
import './components/map.js';
import './components/gallary.js';
